# Build stage
FROM node:22-alpine AS builder
WORKDIR /app
COPY SIGMAV2-APPFRONT-END/SIGMAV2-APP/package*.json ./
RUN npm install

COPY SIGMAV2-APPFRONT-END/SIGMAV2-APP .
RUN npm run build

# Runtime stage
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx/sigmav2-frontend.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
